booksblog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings
import authentication.views
import blog.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        LoginView.as_view(template_name="authentication/login.html", redirect_authenticated_user=True),
        name="login",
    ),
    path("logout/", authentication.views.logout_user, name="logout"),
    path("home/", blog.views.home, name="home"),
    path("signup/", authentication.views.signup_page, name="signup"),
    path("ticket_review/create/", blog.views.ticket_and_review, name="ticket_and_review_create"),
    path("ticket/create/", blog.views.ticket_create, name="ticket_create"),
    path("ticket/request/", blog.views.ticket_request, name="ticket_request"),
    path("ticket/<int:ticket_id>/edit", blog.views.ticket_edit, name="ticket_edit"),
    path("ticket/<int:ticket_id>/delete/", blog.views.ticket_delete, name="ticket_delete"),
    path("review/<int:ticket_id>/create/", blog.views.review_create, name="review_create"),
    path("review/<int:review_id>/edit/", blog.views.review_edit, name="review_edit"),
    path("review/<int:review_id>/delete/", blog.views.review_delete, name="review_delete"),
    path("subscribe/", blog.views.subscribe, name="subscribe"),
    path("unsubscribe/", blog.views.unsubscribe, name="unsubscribe"),
    path("posts/", blog.views.posts, name="posts"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
"""
This module defines Django models.

Model Classes:
    - Ticket: Represents a ticket with associated information, including user, image, and ticket type.
    - Review: Represents a review associated with a ticket, including rating, user, and comments.
"""


from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from PIL import Image


class Ticket(models.Model):
    """
    Represents a ticket with associated information, including user, image, and ticket type.

    Attributes:
        title: CharField
        description: TextField
        user: ForeignKey
        image: ImageField
        uploader: ForeignKey
        time_created: DateTimeField
        ticket_type: CharField ('CREATED', 'REQUEST').
        IMAGE_MAX_SIZE: Tuple (x,y)

    Methods:
        __str__(): Returns a string representation of the ticket, displaying its title.
        resize_image(): Resizes the uploaded image to fit within the specified maximum size.
        save(): Overrides the save method to automatically trigger image resizing on every save.
    """

    TICKET_TYPE_CHOICES = (
        ("CREATED", "Critique"),
        ("REQUEST", "Demande"),
    )
    title = models.CharField(max_length=128, verbose_name="titre")
    description = models.TextField(max_length=1000, blank=True, verbose_name="description")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_tickets")
    image = models.ImageField(null=True, blank=True, verbose_name="image")
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="uploaded_tickets")
    time_created = models.DateTimeField(auto_now_add=True)
    ticket_type = models.CharField(max_length=10, choices=TICKET_TYPE_CHOICES)
    IMAGE_MAX_SIZE = (800, 800)

    def __str__(self):
        return f"{self.title}"

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Review(models.Model):
    """
    Represents a review associated with a ticket, including rating, user, and comments.

    Attributes:
        ticket: ForeignKey
        rating: PositiveSmallIntegerField (0 to 5).
        user: ForeignKey
        headline: CharField
        body: TextField
        time_created: DateTimeField

    Methods:
        __str__(): Returns a string representation of the review, indicating the associated ticket and user.
    """

    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128, verbose_name="titre")
    body = models.TextField(max_length=1000, blank=True, verbose_name="commentaires")
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review for Ticket {self.ticket} by {self.user}"

blog/views.py
"""
This module defines Django views.

   - home(request): Displays the home page with tickets and reviews from followed users.
    - posts(request): Displays posts (tickets and reviews) created by the logged-in user.
    - review_create(request, ticket_id): Creates a new review for a specific ticket.
    - review_edit(request, review_id): Edits an existing review created by the logged-in user.
    - review_delete(request, review_id): Deletes an existing review created by the logged-in user.
    - ticket_create(request): Creates a new ticket.
    - ticket_request(request): Creates a new ticket of type 'REQUEST'.
    - ticket_edit(request, ticket_id): Edits an existing ticket created by the logged-in user.
    - ticket_delete(request, ticket_id): Deletes an existing ticket created by the logged-in user.
    - ticket_and_review(request): Creates a new ticket and an associated review.
    - subscribe(request): Handles user subscriptions.
    - unsubscribe(request): Handles user unsubscriptions.
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from authentication.models import User, UserFollows
from django.contrib import messages
from django.http import HttpResponseForbidden
from . import forms
from . import models
from django.db.models import Q
from itertools import chain


@login_required
def home(request):
    """
        Renders the home page (flux) displaying tickets and reviews from followed users.

    Retrieves tickets and reviews from followed users and the current user, sorts them by creation time,
    and renders the home page with the obtained data.
    """
    following_users = UserFollows.objects.filter(user=request.user).values_list("followed_user", flat=True)
    tickets = models.Ticket.objects.filter(Q(user__in=following_users) | Q(user=request.user)).distinct()
    reviews = models.Review.objects.filter(
        Q(user__in=following_users) | Q(user=request.user) | Q(ticket__user=request.user)
    ).distinct()
    tickets_and_reviews = sorted(chain(tickets, reviews), key=lambda instance: instance.time_created,
                                 reverse=True)

    for instance in tickets_and_reviews:
        if isinstance(instance, models.Ticket):  # Only check reviews for Ticket instances
            instance.user_has_reviewed_ticket = models.Review.objects.filter(
                user=request.user, ticket=instance
            ).exists()
    context = {
        "tickets_and_reviews": tickets_and_reviews,
    }
    return render(request, "blog/home.html", context=context)


@login_required
def posts(request):
    """
     Renders the posts page displaying tickets and reviews created by the logged-in user.

    Retrieves tickets and reviews created by the logged-in user, sorts them by creation time,
    and renders the posts page with the obtained data.

    """
    tickets = models.Ticket.objects.filter(user=request.user).distinct()
    reviews = models.Review.objects.filter(Q(user=request.user)).distinct()
    tickets_and_reviews = sorted(chain(tickets, reviews), key=lambda instance: instance.time_created,
                                 reverse=True)

    context = {
        "tickets_and_reviews": tickets_and_reviews,
    }
    return render(request, "blog/posts.html", context=context)


@login_required
def review_create(request, ticket_id):
    """
    Handles the creation of a new review for a specific ticket.

    If the user already has a review for the ticket, redirects to the home page.
    If the form is submitted with valid data, creates a new review associated with the ticket
    and redirects to the home page.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    existing_review = models.Review.objects.filter(user=request.user, ticket=ticket).first()
    if existing_review:
        return redirect("home")
    if request.method == "POST":
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            return redirect("home")
    else:
        form = forms.ReviewForm()
    return render(request, "blog/review_create.html", {"form": form, "ticket": ticket})


@login_required
def review_edit(request, review_id):
    """
     Handles the editing of an existing review created by the logged-in user.

    If the user is not the owner of the review, redirects to the posts page.
    If the form is submitted with valid data, updates the review and redirects to the posts page.
    """
    review = get_object_or_404(models.Review, id=review_id)
    if request.user != review.user:
        return redirect("posts")
    if request.method == "POST":
        form = forms.ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect("posts")
    else:
        form = forms.ReviewForm(instance=review)
    return render(request, "blog/review_edit.html", {"form": form, "review": review})


@login_required
def review_delete(request, review_id):
    """
    Handles the deletion of an existing review created by the logged-in user.

    If the user is not the owner of the review, redirects to the posts page.
    If the form is submitted with valid data, deletes the review and redirects to the posts page.
    """
    review = get_object_or_404(models.Review, id=review_id)
    if request.user != review.user:
        return redirect("posts")
    if request.method == "POST":
        delete_form = forms.DeleteReviewForm(request.POST)
        if delete_form.is_valid():
            review.delete()
            return redirect("posts")
    else:
        delete_form = forms.DeleteReviewForm()

    context = {
        "review": review,
        "delete_form": delete_form,
    }
    return render(request, "blog/review_delete.html", context)


@login_required
def ticket_create(request):
    """
    Handles the creation of a new ticket.

    If the form is submitted with valid data, creates a new ticket and redirects to the home page.

    """
    if request.method == "POST":
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            if not ticket.image:
                ticket.image = "none.png"
            ticket.user = request.user
            ticket.uploader = request.user
            ticket.ticket_type = "CREATED"
            ticket.save()
            return redirect("home")
    else:
        form = forms.TicketForm()
    return render(request, "blog/ticket_create.html", {"form": form})


@login_required
def ticket_request(request):
    """
     Handles the creation of a new ticket of type 'REQUEST'.

    If the form is submitted with valid data, creates a new ticket of type 'REQUEST' and redirects to the home page.
    """
    if request.method == "POST":
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            if not ticket.image:
                ticket.image = "none.png"
            ticket.user = request.user
            ticket.uploader = request.user
            ticket.ticket_type = "REQUEST"
            ticket.save()
            return redirect("home")
    else:
        form = forms.TicketForm()
    return render(request, "blog/ticket_request.html", {"form": form})


@login_required
def ticket_edit(request, ticket_id):
    """
    Handles the editing of an existing ticket created by the logged-in user.

    If the user is not the owner of the ticket, redirects to the home page.
    If the form is submitted with valid data, updates the ticket and redirects to the posts page.

    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    if request.user != ticket.user:
        return redirect("home")
    if request.method == "POST":
        edit_form = forms.TicketForm(request.POST, request.FILES, instance=ticket)
        if edit_form.is_valid():
            ticket = edit_form.save(commit=False)
            if "image-clear" in request.POST:
                ticket.image = "none.png"
            elif "image" in request.FILES:
                # Update 'image' if a new file is provided
                ticket.image = request.FILES["image"]
            ticket.save()
            return redirect("posts")
    else:
        edit_form = forms.TicketForm(instance=ticket)
    return render(request, "blog/ticket_edit.html", {"edit_form": edit_form, "ticket": ticket})


@login_required
def ticket_delete(request, ticket_id):
    """
    Handles the deletion of an existing ticket created by the logged-in user.

    If the user is not the owner of the ticket, redirects to the posts page.
    If the form is submitted with valid data, deletes the ticket and redirects to the posts page.
    """
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    if request.user != ticket.user:
        return redirect("posts")
    if request.method == "POST":
        delete_form = forms.DeleteTicketForm(request.POST)
        if delete_form.is_valid():
            ticket.delete()
            return redirect("posts")
    else:
        delete_form = forms.DeleteTicketForm()

    context = {
        "ticket": ticket,
        "delete_form": delete_form,
    }
    return render(request, "blog/ticket_delete.html", context)


@login_required
def ticket_and_review(request):
    """
    Handles the creation of a new ticket and an associated review.

    If the forms are submitted with valid data, creates a new ticket and an associated review,
    and redirects to the home page.
    """
    if request.method == "POST":
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)

blog/templates/blog/delete_ticket.html
{% extends 'base.html' %}
{% block content %}

<form method="post" action="{% url 'delete_ticket' ticket.id %}">
  {% csrf_token %}
  <p>Confirmez la suppression du billet "{{ ticket.title }}" :</p>
  {{ delete_form.confirm_delete }}
  <label for="{{ delete_form.confirm_delete.id_for_label }}">Je confirme la suppression</label>
  <br>
  <button type="submit" class="btn btn-danger">Supprimer</button>
  <a href="{% url 'edit_ticket' ticket.id %}" class="btn btn-primary">Annuler</a>
</form>



{% endblock content %}

blog/templates/blog/edit_ticket.html
{% extends 'base.html' %}
{% block content %}

  <h2>Modifier le ticket</h2>
    <form method="post">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary" >Sauvegarder</button>
    </form>


{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load blog_extras %}
{% load static %}
{% block content %}

<h2 class="text-center">Flux: Tickets et Reviews</h2>

<!--boutons-->
<div class="row m-3">
    <div class="col d-flex justify-content-center">
        <form method="get" action="{% url 'ticket_create' %}">
            <button type="submit" class="btn btn-secondary"  >Créer une critique</button>
        </form>
    </div>

    <div class="col d-flex  justify-content-center">
      <form method="get" action="{% url 'ticket_request' %}">
            <button type="submit" class="btn btn-secondary">Demander une critique</button>
        </form>
    </div>

      <div class="col d-flex  justify-content-center">
      <form method="get" action="{% url 'ticket_and_review_create' %}">
            <button type="submit" class="btn btn-secondary">Créer critique et review</button>
        </form>
    </div>
</div>

<!--tickets and reviews-->
<div class="row">
        {% for instance in tickets_and_reviews %}
     <div class="col-12  col-sm-6 col-lg-3">

         {% if instance|model_type == 'Ticket' %}

                    <div class="card m-2"  >
                        <p class="fs-5 fw-bold">{{ instance.get_ticket_type_display }}</p>
                         <img src="{{ instance.image.url }}" class="card-img-top img-fluid w-50 mx-auto m-3"
                              alt="Image du ticket">
                        <div class="card-body">
                            <h3 class="card-title text-center text-primary"> {{ instance.title }}</h3>
                            <p class="card-text overflow-auto" style="max-height: 200px">
                                Publié par <strong>{% display_you instance.user %}</strong> ({{instance.time_created}})
                                <br>
                                <br>
                               <span class="text-decoration-underline"> Description :</span>
                                <br>
                                {{instance.description}}
                            </p>
                            {% if instance.user_has_reviewed_ticket %}
                                <p class="text-primary">Vous avez déjà publié une review sur ce ticket.</p>
                            {% else %}
                                <a href="{% url 'review_create' instance.id %}" class="btn btn-primary">Review</a>
                            {% endif %}
                        </div>
                    </div>

         {% elif instance|model_type == 'Review' %}

            <div class="card m-2" >
                 <p class="fs-5 fw-bold">Review</p>
                    <img class="card-img-top  img-fluid w-50 mx-auto m-3" src="{{ instance.ticket.image.url }}"
                         alt="Review Image">
                    <h3 class="card-title text-center text-primary "> {{ instance.headline}} </h3>
                    <div class="card-body">
                        <p> <span class="text-decoration-underline"> Rating:</span>
                            {% if instance.rating == 5 %}
                                <img src="{% static 'images/stars5.png' %}" alt="Image for Rating 5">
                            {% elif instance.rating == 4 %}
                                <img src="{% static 'images/stars4.png' %}" alt="Image for Rating 4">
                            {% elif instance.rating == 3 %}
                                <img src="{% static 'images/stars3.png' %}" alt="Image for Rating 3">
                            {% elif instance.rating == 2 %}
                                <img src="{% static 'images/stars4.png' %}" alt="Image for Rating 2">
                            {% elif instance.rating == 1 %}
                                <img src="{% static 'images/stars1.png' %}" alt="Image for Rating 1">
                            {% endif %}
                        </p>

                        <p class="card-text">
                            Publié par <strong>{% display_you instance.user %}</strong>  ({{instance.time_created}})
                            <br>
                            <br>
                            <span class="text-decoration-underline"> Commentaires:</span>
                            <br>
                            {{ instance.body }}
                        </p>
                    </div>
            </div>
         {% endif %}
     </div>
        {% endfor %}
</div>


{% endblock content %}

blog/templates/blog/posts.html
{% extends 'base.html' %}
{% load blog_extras %}
{% load static %}
{% block content %}


<h3 class="text-center">Voici vos posts:</h3>

<div class="row">
    {% for instance in tickets_and_reviews %}

        <div class="col-12  col-sm-6 col-lg-3">

            {% if instance|model_type == 'Ticket' %}

                <div class="card m-2"  >
                    <p class="fs-5 fw-bold">{{ instance.get_ticket_type_display }}</p>
                    <img src="{{ instance.image.url }}" class="card-img-top  img-fluid w-50 mx-auto m-3"
                         alt="Image du ticket">
                    <div class="card-body">
                        <h3 class="card-title text-center text-primary"> {{ instance.title }}</h3>
                        <p class="card-text overflow-auto" style="max-height: 200px">
                            Publié par <strong>{% display_you instance.user %}</strong> ({{instance.time_created}})
                            <br>
                            <br>
                           <span class="text-decoration-underline"> Description :</span>
                            <br>
                            {{instance.description}}
                        </p>
                        <a href="{% url 'ticket_edit' instance.id  %}" class="btn btn-primary">Modifier</a>
                        <a href="{% url 'ticket_delete' instance.id  %}" class="btn btn-primary">Supprimer</a>
                    </div>
                </div>

            {% elif instance|model_type == 'Review' %}

                <div class="card m-2" >
                    <p class="fs-5 fw-bold">Review</p>
                    {% if instance.ticket.image %}
                        <img class="card-img-top  img-fluid w-50 mx-auto m-3" src="{{ instance.ticket.image.url }}"
                             alt="Review Image">
                    {% endif %}
                    <h3 class="card-title text-center text-primary "> {{ instance.headline}} </h3>
                    <div class="card-body">
                        <p> <span class="text-decoration-underline"> Note:</span>
                            {% if instance.rating == 5 %}
                                <img src="{% static 'images/stars5.png' %}" alt="Image for Rating 5">
                            {% elif instance.rating == 4 %}
                                <img src="{% static 'images/stars4.png' %}" alt="Image for Rating 4">
                            {% elif instance.rating == 3 %}
                                <img src="{% static 'images/stars3.png' %}" alt="Image for Rating 3">
                            {% elif instance.rating == 2 %}
                                <img src="{% static 'images/stars4.png' %}" alt="Image for Rating 2">
                            {% elif instance.rating == 1 %}
                                <img src="{% static 'images/stars1.png' %}" alt="Image for Rating 1">
                            {% endif %}
                        </p>

                        <p class="card-text">
                            Publié par <strong>{% display_you instance.user %}</strong>  ({{instance.time_created}})
                            <br>
                            <br>

                            <span class="text-decoration-underline"> Commentaires :</span>
                            <br>
                            {{ instance.body }}
                        </p>
                        <p>
                        <a href="{% url 'review_edit' instance.id %}" class="btn btn-primary">Modifier</a>
                        <a href="{% url 'review_delete' instance.id%}" class="btn btn-primary">Supprimer</a>
                        </p>
                    </div>
                </div>

            {% endif %}

        </div>
    {% endfor %}
</div>

{% endblock content %}

blog/templates/blog/review_create.html
{% extends 'base.html' %}
{% block content %}

<h2>Création de review</h2>

<p>Le ticket sélectionné est: <strong>{{ ticket.title }} </strong></p>
<img src="{{ ticket.image.url }}" alt="ticket_image">

<form method="post" action="{% url 'review_create' ticket.id %}">

  {% csrf_token %}
  <div class="form-group">
      <label for="{{ form.rating.id_for_label }}" class="form-label">Note :</label>
      <div id="{{ form.rating.id_for_label }}" class="form-check form-check-inline">
          {% for radio in form.rating %}
            {{ radio }}
          {% endfor %}
      </div>
  </div>

  <div class="form-group">
    <label for="{{ form.headline.id_for_label }}" class="form-label">Titre :</label>
        {{ form.headline }}
  </div>

  <div class="form-group">
    <label for="{{ form.body.id_for_label }}" class="form-label">Commentaire :</label>
      {{ form.body }}
  </div>

  <button type="submit" >Publier</button>
</form>

<br>

<form method="get" action="{% url 'home' %}">
    <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}

blog/templates/blog/review_delete.html
{% extends 'base.html' %}
{% block content %}

<form method="post" action="{% url 'review_delete' review.id %}">
  {% csrf_token %}
  <p>Confirmez la suppression de la review "{{ review.headline}}" :</p>
  {{ delete_form.confirm_delete }}
  <label for="{{ delete_form.confirm_delete.id_for_label }}">Je confirme la suppression</label>
  <br>
  <button type="submit" class="btn btn-danger">Supprimer</button>
  <a href="{% url 'posts' %}" class="btn btn-primary">Annuler</a>
</form>

{% endblock content %}

blog/templates/blog/review_edit.html
{% extends 'base.html' %}
{% block content %}

<h2>Modifier Review</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sauvegarder</button>
</form>

<br>

<form method="get" action="{% url 'posts' %}">
  <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}

blog/templates/blog/subscribe.html
{% extends 'base.html' %}
{% block content %}

<h2>Personnes auxquelles vous êtes abonné :</h2>

<ul class="list-unstyled">
    {% for username in following %}
        <li>
            {{ username }}
            <form class= "d-inline" method="post" action="{% url 'unsubscribe' %}">
                {% csrf_token %}
                <input type="hidden" name="unfollow_username" value="{{ username }}">
                <button type="submit">Se désabonner</button>
            </form>
        </li>
    {% endfor %}
</ul>

<h2>Personnes abonnées à vous :</h2>

<ul class="list-unstyled">
    {% for username in followers %}
        <li>{{ username }}</li>
    {% endfor %}
</ul>

<h2>Suivre d'autres utilisateurs</h2>

<form method="post" action="{% url 'subscribe' %}">
    {% csrf_token %}
    {{ form.username.errors }}
    {{ form.username.label_tag }}
    {{ form.username }}
    <button type="submit">S'abonner</button>
</form>

{% endblock content %}

blog/templates/blog/ticket_and_review_create.html
{% extends 'base.html' %}
{% block content %}

<h2 >Création ticket et review</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <h3 class="text-primary">Ticket</h3>
    {{ ticket_form.as_p }}

    <div class="form-group">
      <label for="{{ review_form.rating.id_for_label }}" class="form-label">Note :</label>
      <div id="{{ review_form.rating.id_for_label }}" class="form-check form-check-inline">
        {% for radio in review_form.rating %}
          {{ radio }}
        {% endfor %}
      </div>
    </div>

    <h3 class="text-primary">Review</h3>

    <div class="form-group">
      <label for="{{ review_form.headline.id_for_label }}" class="form-label">Titre :</label>
      {{ review_form.headline }}
    </div>

    <div class="form-group">
      <label for="{{ review_form.body.id_for_label }}" class="form-label">Commentaire :</label>
      {{ review_form.body }}
    </div>

    <button type="submit">Sauvegarder</button>
</form>

<br>

<form method="get" action="{% url 'home' %}">
    <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}

blog/templates/blog/ticket_create.html
{% extends 'base.html' %}
{% block content %}

<h2>Création de ticket</h2>

<form method="post" enctype="multipart/form-data" >
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" >Publier</button>
</form>

<br>

<form method="get" action="{% url 'home' %}">
   <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}

blog/templates/blog/ticket_delete.html
{% extends 'base.html' %}
{% block content %}

<form method="post" action="{% url 'ticket_delete' ticket.id %}">
  {% csrf_token %}
  <p>Confirmez la suppression du billet "{{ ticket.title }}" :</p>
  {{ delete_form.confirm_delete }}
  <label for="{{ delete_form.confirm_delete.id_for_label }}">Je confirme la suppression</label>
  <br>
  <button type="submit" class="btn btn-danger">Supprimer</button>
  <a href="{% url 'posts' %}" class="btn btn-primary">Annuler</a>
</form>

{% endblock content %}

blog/templates/blog/ticket_edit.html
{% extends 'base.html' %}
{% block content %}

<h2>Modifier le ticket</h2>

<form method="post" enctype="multipart/form-data">
    {{ edit_form.as_p }}
    {% csrf_token %}
    <button type="submit" >Sauvegarder</button>
</form>

<br>

<form method="get" action="{% url 'posts' %}">
    <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}

blog/templates/blog/ticket_request.html
{% extends 'base.html' %}
{% block content %}

<h2>Demande ticket</h2>

<form method="post" enctype="multipart/form-data" >
    {{ form.as_p }}
       {% csrf_token %}
    <button type="submit" >Publier</button>
</form>

<br>

<form method="get" action="{% url 'home' %}">
   <button type="submit" class="btn btn-secondary">Annuler</button>
</form>

{% endblock content %}